### ISSUE TITLE
Parameter schema object doesn't get linked to definition

### ISSUE THREAD

**Issue by andrewwuan** [jmcarp/flask-apispec#62]
When I use a marshmallow schema object in parameters, it doesn't linked to definitions automatically. This is causing problems when I use `swagger-codegen`, because all the parameter objects are of `Body` class (thus I have `Body`, `Body1`, `Body2`, etc.), instead of the real schema class they are defined.

Here's the code snippet to reproduce the issue:

```python
from flask_script import Manager

from flask import Flask, make_response
from flask_restful import Api
from flask_apispec import FlaskApiSpec, MethodResource, use_kwargs, marshal_with

from marshmallow import fields, Schema

app = Flask(__name__)
api = Api(app)

class PetSchema(Schema):
    class Meta:
        fields = ('name',)

    name = fields.String()


class PetResource(MethodResource):

    @marshal_with(PetSchema)
    def get(self, pet_id):
        return {
            'name': 'Jerry'
        }

    @use_kwargs(PetSchema)
    @marshal_with(PetSchema, code=201)
    def post(self, **kwargs):
        return {
            'name': 'Jerry'
        }

api.add_resource(PetResource, '/pet/<string:pet_id>')

docs = FlaskApiSpec(app)
docs.spec.definition('PetSchema', schema=PetSchema)
docs.register(PetResource)


manager = Manager(app)

if __name__ == '__main__':
    manager.run()
```

By running `python app.py runserver` and going to `localhost:5000/swagger`, I get the following Swagger JSON:

```json
{
  "definitions": {
    "PetSchema": {
      "properties": {
        "name": {
          "type": "string"
        }
      }, 
      "type": "object"
    }
  }, 
  "info": {
    "title": "flask-apispec", 
    "version": "v1"
  }, 
  "parameters": {}, 
  "paths": {
    "/pet/{pet_id}": {
      "get": {
        "parameters": [
          {
            "in": "path", 
            "name": "pet_id", 
            "required": true, 
            "type": "string"
          }
        ], 
        "responses": {
          "default": {
            "description": "", 
            "schema": {
              "$ref": "#/definitions/PetSchema"
            }
          }
        }
      }, 
      "post": {
        "parameters": [
          {
            "in": "body", 
            "name": "body", 
            "required": false, 
            "schema": {
              "properties": {
                "name": {
                  "type": "string"
                }
              }, 
              "type": "object"
            }
          }, 
          {
            "in": "path", 
            "name": "pet_id", 
            "required": true, 
            "type": "string"
          }
        ], 
        "responses": {
          "201": {
            "description": "", 
            "schema": {
              "$ref": "#/definitions/PetSchema"
            }
          }
        }
      }
    }
  }, 
  "swagger": "2.0", 
  "tags": []
}
```

One can see that while `"$ref": "#/definitions/PetSchema"` is correctly placed in `responses`, in `parameters` however, it's broken down. This causes `swagger-codegen` to fail to recognize the schema class, and use class `Body` in the generated code, which is a problem when the app have several routes with schema in parameters.

Is this an issue in `apispec` or `flask-apispec`? Any feedback would be much appreciated!

**Comment by omersyuksel** [comment]
I am having the same issue. Is anyone aware of workarounds for this one?

**Comment by DStape** [comment]
Hello @andrewwuan, @omersyuksel, I was experiencing the same issue, I opened #92 which should solve this problem. Would be great if either of you could test this out and see if if fixes the issue in your own setups/environments.

Thanks,
David.

**Comment by DStape** [comment]
Looking at your example, remember that you also need enable the appropriate apispec plugin, e.g.:
``` app.config.update({
             'APISPEC_SPEC': APISpec(
                 title='pets',
                 version='v1',
                 plugins=['apispec.ext.marshmallow'],
             )```

**Comment by mihhdu** [comment]
Hi! I have run @andrewwuan's example with specifying a APISpec spec, and still have the same error. Is there anyone who has managed to get passed this?
